#!/bin/sh

set -- "
    dockerfile-language-server-nodejs
    @angular/cli @angular/language-server
    typescript typescript-language-server
    prettier
    vscode-langservers-extracted
    @tailwindcss/language-server
    sql-language-server
    pyright
    cspell 
    @fsouza/prettierd
"

npm install -g $@
