#!/bin/sh

npm install -g dockerfile-language-server-nodejs
npm install -g @angular/cli @angular/language-server
npm install -g typescript typescript-language-server
npm install -g prettier
npm install -g vscode-langservers-extracted
npm install -g @tailwindcss/language-server
npm install -g sql-language-server
npm install -g pyright
